name: Build Sphinx docs

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'stable/**'
  pull_request:
    branches:
      - main
      - 'stable/**'

jobs:
  docs:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox
          sudo apt-get update
          sudo apt-get install -y pandoc
      - name: Build docs
        shell: bash
        run: |
          tox -e docs
      - name: Upload docs artifact
        if: always()
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/_build/html
