name: Lint

on:
  push:
    branches:
      - main
      - 'stable/**'
  pull_request:
    branches:
      - main
      - 'stable/**'

jobs:
  lint:
    name: lint check
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install tox
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - name: Run lint check
        run: |
          tox -e lint
